markdown: kramdown
Rouge: true
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
name: Sijin LI


google_analytics: UA-42209870-1
disqus_shortname: sijin

paginate:  3

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

pages_list:       
  About: '/about'
  Posts: '/posts'

gems:
  - jekyll-gist
  - jekyll-sitemap