markdown: kramdown
Rouge: true
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
name: Sijin LI


paginate:  3

collections:
	categories:
	output:true
	permalink:/blog/category/:name/

pages_list:       
  About: '/about'
  Posts: '/posts'

				