markdown: kramdown
Rouge: true
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
name: Sijin LI


paginate:  3

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  tags:
    output: true
    permalink: /blog/tag/:name/

pages_list:       
  About: '/about'
  Posts: '/posts'