markdown: kramdown
Rouge: true
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
name: Sijin LI


paginate:  3

collections:
  my_categories:
    output: true
  tag:
    output: true 

pages_list:       
  About: '/about'
  Posts: '/posts'